### ISSUE TITLE
Can you provide a Linux version of libNGIOUniversal.dylib

### ISSUE THREAD

**Issue by hansaplasst** [VernierST/labquest-py#7]
I would like to run this in Linux. I'm willing to test the change.
Cheers!

**Comment by sswartley** [comment]
Hello,

I'm afraid we do not have a shared library for Linux and will not be creating one. Note that our Go Direct sensors do have Python support in Linux.

All the best,

Sam

**Comment by hansaplasst** [comment]
Why not use [libusb](https://pypi.org/project/libusb/)?

**Comment by stocktonkincade** [comment]
We do use libusb for our internal Linux implementation of the NGIO library. The problem is that we do not have pre-compiled shared libraries for every Linux architecture, and we do not provide the library source code for users to compile against their intended architectures. It is a proprietary source base.

**Comment by hansaplasst** [comment]
Thanks for clarifying!
Best regards,

Hans
